export default {
  _prodcuts: [
    
    {
      "ProductId": "HT-1119",
      "Category": "Accessories",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 88,
      "WeightUnit": "G",
      "Description": "Universal Travel Adapter",
      "Name": "Travel Adapter",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1119.jpg",
      "Status": "Available",
      "Quantity": 10,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 79,
      "Width": 2,
      "Depth": 3.1,
      "Height": 3.9,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1258",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 2.5,
      "WeightUnit": "KG",
      "Description": "8-inch Multitouch HD Screen (2000 x 1500) 32GB Internal Memory, Wireless N Wi-Fi, Bluetooth, GPS Enabled, 1.5 GHz Quad-Core Processor",
      "Name": "Cepat Tablet 8",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1258.jpg",
      "Status": "Available",
      "Quantity": 24,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 529,
      "Width": 38,
      "Depth": 21,
      "Height": 3.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-8000",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 4,
      "WeightUnit": "KG",
      "Description": "Notebook with 2,80 GHz dual core, 4 GB DDR3 SDRAM, 500 GB Hard Disc, Windows 8",
      "Name": "ITelO FlexTop I4000",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-8000.jpg",
      "Status": "Available",
      "Quantity": 11,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 799,
      "Width": 31,
      "Depth": 19,
      "Height": 3.1,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-8001",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 4.2,
      "WeightUnit": "KG",
      "Description": "Notebook with 2,80 GHz dual core, 8 GB DDR3 SDRAM, 500 GB Hard Disc, Windows 8",
      "Name": "ITelO FlexTop I6300c",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-8001.jpg",
      "Status": "Available",
      "Quantity": 20,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 799,
      "Width": 32,
      "Depth": 20,
      "Height": 3.4,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-8002",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 3.5,
      "WeightUnit": "KG",
      "Description": "Notebook with 2,80 GHz quad core, 4 GB DDR3 SDRAM, 1000 GB Hard Disc, Windows 8",
      "Name": "ITelO FlexTop I9100",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-8002.jpg",
      "Status": "Available",
      "Quantity": 20,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 1199,
      "Width": 38,
      "Depth": 21,
      "Height": 4.1,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-8003",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 3.8,
      "WeightUnit": "KG",
      "Description": "Notebook with 2,80 GHz quad core, 8 GB DDR3 SDRAM, 1000 GB Hard Disc, Windows 8",
      "Name": "ITelO FlexTop I9800",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-8003.jpg",
      "Status": "Available",
      "Quantity": 22,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 1388,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "PF-1000",
      "Category": "Accessories",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 0.01,
      "WeightUnit": "KG",
      "Description": "Flyer for our product palette",
      "Name": "Flyer",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/PF-1000.jpg",
      "Status": "Available",
      "Quantity": 33,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 0,
      "Width": 46,
      "Depth": 30,
      "Height": 3,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9999",
      "Category": "Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 3.8,
      "WeightUnit": "KG",
      "Description": "10.1-inch Multitouch HD Screen (1280 x 800), 16GB Internal Memory, Wireless N Wi-Fi; Bluetooth, GPS Enabled, 1GHz Dual-Core Processor",
      "Name": "Maxi Tablet",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9999.jpg",
      "Status": "Available",
      "Quantity": 20,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 749,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9998",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 0.75,
      "WeightUnit": "KG",
      "Description": "5 Megapixel Camera, Wi-Fi 802.11 b/g/n, Bluetooth, GPS Available-GPS support",
      "Name": "Smartphone Beta",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9998.jpg",
      "Status": "Available",
      "Quantity": 21,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 30,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9997",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 3.8,
      "WeightUnit": "KG",
      "Description": "6-Inch E Ink Screen, Access To e-book Store, Adjustable Font Styles and Sizes, Stores Up To 1,000 Books",
      "Name": "e-Book Reader ReadMe",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9997.jpg",
      "Status": "Available",
      "Quantity": 23,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 33,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9996",
      "Category": "Accessories",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 0.03,
      "WeightUnit": "KG",
      "Description": "Stylish tablet pouch, protects from scratches, color: black",
      "Name": "Tablet Pouch",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9996.jpg",
      "Status": "Available",
      "Quantity": 34,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 20,
      "Width": 25,
      "Depth": 40,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9995",
      "Category": "Accessories",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Titanium",
      "WeightMeasure": 0.02,
      "WeightUnit": "KG",
      "Description": "Durable high quality plastic bump-sleeve, lightweight, protects from scratches, rubber coating, multiple colors available, Accurate design and cut-outs for your device, snap-on design",
      "Name": "Smartphone Cover",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9995.jpg",
      "Status": "Available",
      "Quantity": 23,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 15,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9994",
      "Category": "Accessories",
      "MainCategory": "TV, Video & HiFi",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 3.8,
      "WeightUnit": "KG",
      "Description": "1920x1080 Full HD, image stabilization reduces blur, 27x Optical / 32x Extended Zoom, wide angle Lens, 2.7\" wide LCD display",
      "Name": "Camcorder View",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9994.jpg",
      "Status": "Available",
      "Quantity": 50,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 1388,
      "Width": 48,
      "Depth": 31,
      "Height": 27,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9993",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 3.8,
      "WeightUnit": "KG",
      "Description": "7 inch 1280x800 HD display (216 ppi), Quad-core processor, 16 GB internal storage, 4325 mAh battery (Up to 8 hours of active use)",
      "Name": "Mini Tablet",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9993.jpg",
      "Status": "Available",
      "Quantity": 10,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 833,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9992",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 0.75,
      "WeightUnit": "KG",
      "Description": "7 inch 1280x800 HD display (216 ppi), Quad-core processor, 16 GB internal storage (actual formatted capacity will be less), 4325 mAh battery (Up to 8 hours of active use), white or black",
      "Name": "Smartphone Alpha",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9992.jpg",
      "Status": "Available",
      "Quantity": 13,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 599,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-9991",
      "Category": "Accessories",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 0.02,
      "WeightUnit": "KG",
      "Description": "Button Clasp, Quality Material, 100% Leather, compatible with many smartphone models",
      "Name": "Smartphone Leather Case",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-9991.jpg",
      "Status": "Available",
      "Quantity": 12,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 25,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1251",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 4.2,
      "WeightUnit": "KG",
      "Description": "Flexible Laptop with 2,5 GHz Quad Core, 15\" HD TN, 16 GB DDR SDRAM, 256 GB SSD, Windows 10 Pro",
      "Name": "Astro Laptop 1516",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1251.jpg",
      "Status": "Available",
      "Quantity": 23,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 989,
      "Width": 30,
      "Depth": 18,
      "Height": 3,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1252",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 0.75,
      "WeightUnit": "KG",
      "Description": "6 inch 1280x800 HD display (216 ppi), Quad-core processor, 8 GB internal storage (actual formatted capacity will be less), 3050 mAh battery (Up to 8 hours of active use), grey or black",
      "Name": "Astro Phone 6",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1252.jpg",
      "Status": "Available",
      "Quantity": 28,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 649,
      "Width": 8,
      "Depth": 6,
      "Height": 1.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1253",
      "Category": "Laptops",
      "MainCategory": "Computer Systems",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 4.2,
      "WeightUnit": "KG",
      "Description": "Flexible Laptop with 2,5 GHz Dual Core, 14\" HD+ TN, 8 GB DDR SDRAM, 324 GB SSD, Windows 10 Pro",
      "Name": "Benda Laptop 1408",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1253.jpg",
      "Status": "Available",
      "Quantity": 27,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 976,
      "Width": 30,
      "Depth": 18,
      "Height": 3,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1254",
      "Category": "Flat Screens",
      "MainCategory": "Computer Components",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 15,
      "WeightUnit": "KG",
      "Description": "Optimum Hi-Resolution Widescreen max. 1920 x 1080 @ 85Hz, Dot Pitch: 0.27mm, HDMI, Discontinued-Sub",
      "Name": "Bending Screen 21HD",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1254.jpg",
      "Status": "Available",
      "Quantity": 23,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 250,
      "Width": 37,
      "Depth": 12,
      "Height": 36,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1255",
      "Category": "Flat Screens",
      "MainCategory": "Computer Components",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 16,
      "WeightUnit": "KG",
      "Description": "Optimum Hi-Resolution Widescreen max. 2048 x 1080 @ 85Hz, Dot Pitch: 0.27mm, HDMI, Discontinued-Sub",
      "Name": "Broad Screen 22HD",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1255.jpg",
      "Status": "Available",
      "Quantity": 5,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 270,
      "Width": 39,
      "Depth": 12,
      "Height": 38,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1256",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 0.75,
      "WeightUnit": "KG",
      "Description": "7 inch 1280x800 HD display (216 ppi), Quad-core processor, 16 GB internal storage (actual formatted capacity will be less), 4325 mAh battery (Up to 8 hours of active use), white or black",
      "Name": "Cerdik Phone 7",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1256.jpg",
      "Status": "Available",
      "Quantity": 19,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 549,
      "Width": 9,
      "Depth": 15,
      "Height": 1.5,
      "DimUnit": "cm"
    },
    {
      "ProductId": "HT-1257",
      "Category": "Smartphones and Tablets",
      "MainCategory": "Smartphones & Tablets",
      "TaxTarifCode": "1",
      "SupplierName": "Ultrasonic United",
      "WeightMeasure": 2.8,
      "WeightUnit": "KG",
      "Description": "10.5-inch Multitouch HD Screen (1280 x 800), 16GB Internal Memory, Wireless N Wi-Fi; Bluetooth, GPS Enabled, 1GHz Dual-Core Processor",
      "Name": "Cepat Tablet 10.5",
      "ProductPicUrl": "https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/HT-1257.jpg",
      "Status": "Available",
      "Quantity": 17,
      "UoM": "PC",
      "CurrencyCode": "EUR",
      "Price": 549,
      "Width": 48,
      "Depth": 31,
      "Height": 4.5,
      "DimUnit": "cm"
    }
  ],
  get prodcuts() {
    return this._prodcuts;
  },
  set prodcuts(value) {
    this._prodcuts = value;
  },
}
